doc/mcpdft/README.md, setup.py
Accidentally spelled it "pyscf-force." Oops. Also, the urls in doc/mcpdft/README.md have been updated.
=> Typo in setup.py; update doc/mcpdft/README.md

pyscf/mcpdft/_libxc.py, pyscf/prop/trans_dip_moment/mspdft.py
I accidentally left imports from `mrh` in the CMS-PDFT transition dipole moments code. Fortunately there was no issue pointing those to `pyscf`.
ETA: Also fixed an edge case where hybrid on-top functionals with lambda = 0 gives an error.
=> import from mrh -> import from pyscf plus hybrid fnal edge case bug

pyscf/lib/CMakeLists.txt
Looks like https://github.com/MatthewRHermes/mrh/pull/15 is not applied after migrating to pyscf-forge. Applied in this PR.
=> include user-defined cint.h directory for cmake

examples/mcpdft/43-multi_state_mix.py, pyscf/mcpdft/_dms.py, pyscf/mcpdft/lpdft.py, pyscf/mcpdft/mcpdft.py, pyscf/mcpdft/test/test_lpdft.py, pyscf/mcpdft/xmspdft.py
Implementation of StateAverageMix solvers for L-PDFT. Since the L-PDFT Hamiltonian transforms as the real electronic Hamiltonian, it maintains the same spatial and spin symmetries. This is unlike in other MS-PDFT methods like CMS-PDFT and XMS-PDFT where this behavior is not really well-defined. 
Here I introduce a new function `multi_state_mix()` which acts just like the correspondence between `state_average` and `multi_state` as to the `state_average_mix()` method. The underlying functionality of `make_lpdft_ham()` is generalized to multiple solvers so that it constructs the matrix within each space defined by the solver, but in an efficient manner (ie only a single quadrature calculation). I deal with the necessary headaches of having a list of hamiltonian matrices, diagonalizing, as …
=> Lpdft samix

pyproject.toml
pip>23.1 no longer emulates setup.py install; see https://github.com/pypa/pip/issues/8559. Is this the way we should go @sunqm? See issue #19
=> Issue #19 pyprojecttoml

pyscf/grad/test/test_grad_mspdft.py, pyscf/mcpdft/test/test_mcpdft.py, pyscf/mcpdft/test/test_otfnal.py
PySCF PR #[1623](https://github.com/pyscf/pyscf/pull/1623) made symmetry FCI solvers unable to interpret a 3d ndarray (`shape=(n,*,*)`) as a list of _n_ CI vectors, which was used by one unit test. Here, those are explicitly cast to a list of 2d ndarrays. Also remove a certain unit test case which was always undefined behavior. This presumes PySCF PR #[1721](https://github.com/pyscf/pyscf/pull/1721). See issue #19 and PR #20 concerning the inevitable CI failure. I redid this from PR #18 after getting sick of my master branch git log constantly having a bunch of meaningless "merge master from origin" lines in it.
=> pyscf PR #1623 compatibility and np.int deprecation

pyscf/grad/cmspdft.py, pyscf/grad/mcpdft.py, pyscf/mcpdft/lpdft.py, pyscf/mcpdft/xmspdft.py, pyscf/prop/dip_moment/mcpdft.py, pyscf/prop/dip_moment/mspdft.py
This PR either replaces `np.einsum` with `np.tensordot` or `np.dot`. However, if neither of the above 2 is feasibly, then it replaced by the `pyscf.lib.einsum` call instead. Only if none of these calls are valid, is it left as a np.einsum.
=> Upgrade einsum calls

pyscf/mcpdft/lpdft.py, pyscf/mcpdft/mcpdft.py, pyscf/mcpdft/pdft_veff.py
Computes $E_\mathrm{ot}$, $V_{pq}$, and $v_{pqrs}$ in the same quadrature loop. Before, $E_\mathrm{ot}$ was computed in a separate loop from $V_{pq}$ and $v_{pqrs}$.
=> Speed Up L-PDFT

pyscf/mcpdft/_dms.py, pyscf/mcpdft/mcpdft.py, pyscf/mcpdft/test/test_lpdft.py, pyscf/prop/trans_dip_moment/test/test_cmspdft_tdm.py
Update some class initializations to correspond to the PySCF MCSCF refactor in PySCF PR #1859. This is the minimal necessary change to pass existing unit tests.
=> Compatibility w/ PySCF #1859 (issue #40)

doc/mcpdft/README.md, examples/nac/01-cmspdft_nac.py, pyscf/mcpdft/__init__.py, pyscf/mcpdft/mspdft.py, pyscf/nac/mspdft.py, pyscf/nac/test/test_nac_cmspdft.py
Migrate CMS-PDFT nonadiabatic coupling from [mrh](https://github.com/MatthewRHermes/mrh) to PySCF-forge. Originally authored by @MatthewRHermes and Paul Calio. Has same calling signature as SA-CASSCF NACs as described in that [PR](https://github.com/pyscf/pyscf/pull/2046). 
Note that this requires the SA-CASSCF NACs to be in the main PySCF repository and will not pass CI until then.
=> CMS-PDFT Nonadiabatic Coupling

pyscf/grad/lpdft.py, pyscf/grad/test/test_grad_mcpdft.py, pyscf/mcpdft/chkfile.py, pyscf/mcpdft/lpdft.py, pyscf/mcpdft/mcpdft.py, pyscf/mcpdft/test/test_lpdft.py, pyscf/mcpdft/test/test_mcpdft.py
Add MC-PDFT and L-PDFT chkfile support under `pdft` key. For certain values, it uses hard links to the corresponding data in the `mcscf` group. Writes the following data to the chkfile:
MC-PDFT:
- `e_tot`
- `e_ot`
- `e_states` (if state-averaged)
- `e_mcscf`
- `mo_coeff` (as a hard link to `mcscf/mo_coeff`)
- `ci` (as a hard link to `mcscf/ci`, if exists)
L-PDFT:
- `e_tot`
- `e_states`
- `e_mcscf`
- `ci` (if `chk_ci=True` and the L-PDFT adiabatic CI vectors)
=> PDFT Chkfile Support

pyscf/mcpdft/mcpdft.py
Previously EDA is hardcoded for the CASSCF wavefunction only. I added the functionality to do this analysis for the DMRG-PDFT as well.
=> Energy Decomposition Analysis adopted for general MCSCF 

pyscf/mcpdft/_libxc.py, pyscf/mcpdft/mspdft.py
`isinstance (*, int) -> isinstance (*, (int, np.integer))`
=> check integer correctly to account for pyscf #2377

.github/workflows/ci.yml
Partially address #67, in particular enabling the update to trexio. Higher Python versions will require PySCF 2.7.
=> Update GitHub actions to Python 3.8

.github/workflows/publish.yml, CHANGELOG, NOTICE, README.md, setup.py
Add CHANGELOG
@MatthewRHermes The available features are shortly summarized in the CHANGELOG file. Please correct the description in that file if you notice any issues.
=> Bump version

pyscf/mcpdft/mcpdft.py, pyscf/mcpdft/test/test_mcpdft.py
Address #65.
Now `get_energy_decomposition` returns `e_nuc`, `e_1e`, `e_coul`, `e_otx`/`e_otxc`, `e_otc`, `e_ncwfn`, but if the energy is computed with a hybrid functional, it returns the properly scaled `e_otx`/`e_otxc`, `e_otc`, `e_ncwfn` terms such that the energy of each state is the sum of all elements returned. 
Note that `get_energy_decomposition` for non-hybrid functional returns the full `e_ncwfn` and the energy of each state is equal to the sum of elements except `e_ncwfn` (prior behavior).
=> MC-PDFT Hybrid Energy Decomposition

pyscf/tools/trexio.py
Hello,
For a specific reason, I needed to register my determinants into TREXIO, so I modified the code to accomplish this.
Since the functions use the MCSCF object and `mcscf_to_trexio` has not been developed yet, it might be beneficial to register the determinants infos into a different TREXIO file compared to the one used for the mf part. Therefore, this final TREXIO file only contains:
- Number of MOs
- Number of alpha electrons
- Number of beta electrons
- Total number of electrons
- Number of determinants
- Coefficients
- Determinants in bitfield format
The user can also set a threshold to register into the TREXIO file only the determinants with coefficients higher than the user-defined value. If no value is provided by the user, the full list of determinants generated by the PySCF …
=> The User can now register its determinant into trexio format

pyscf/tools/test/test_trexio.py, pyscf/tools/trexio.py
@matthew-hennefarth 
Sorry for my late response. Today, I have implemented lines to write ECP information to a TREXIO file. Please have a look at my pull request.
The ECP part works. However, a problem I found is that the `cc-pVXZ` basis sets accompanied with `ccECP`, which are often used for QMC calculations, did not pass the following assertion line in `trexio.py`.
>       assert all(mol._bas[:,gto.NCTR_OF] == 1)
Would you give me a clue for solving this problem?
#60
=> Implemented the ECP part and added several missing factors in the TREXIO interface.

pyscf/tools/test/test_trexio.py, pyscf/tools/trexio.py
I have implemented PBC for Gamma point (i.e., real wavefunction) in the `trexio` converter.
An example is:
```
import numpy as np
from pyscf.pbc import gto, dft
from pyscf.tools import trexio
cell = gto.M(
verbose = 4,
a = np.eye(3)*3.5668,
atom = '''C     0.      0.      0.    
C     0.8917  0.8917  0.8917
C     1.7834  1.7834  0.    
C     2.6751  2.6751  0.8917
C     1.7834  0.      1.7834
C     2.6751  0.8917  2.6751
C     0.      1.7834  1.7834
C     0.8917  2.6751  2.6751'''
)
cell.output = pyscf_output
cell.charge = 0
cell.spin = 0
cell.symmetry = False
cell.basis = 'ccecp-ccpvdz'
cell.exp_to_discard = 0.2
cell.ecp = 'ccecp'
cell.build(cart=False)
kpt = [0.0, 0.0, 0.0]
mf = dft.rks.RKS(cell, kpt=kpt)
mf.xc = "lda_x,lda_c_pz"
mf.chkfile = "pyscf_diamond.chk"
total_energy = …
```
=> Implemented PBC for Gamma point (real wavefunction)

CHANGELOG, pyscf/mcdcft/dcfnal.py, setup.py
@Dayou-Zhang I'm not sure if the citation in dcfnal.py is accurate. Please correct me and add more if I missed any.
=> Release 1.0.2

pyscf/mcpdft/__init__.py
In the current implementation, using a CAS object calculated at the $$\Gamma$$-point (PBC) for MCPDFT does not raise an error. However, in the case of periodic boundary conditions, one needs to use specific quadrature grids, which have not been implemented yet. Therefore, in this PR, I have added a function that checks the `mol` object during the initialization of the MCPDFT object and raises an error if a `cell` object is found.
@MatthewRHermes
=> Sanity Check of the mol object in MCPDFT

pyscf/lrdf/test/test_lrdf.py, pyscf/msdft/tests/test_noci.py
msdft/test_noci: SCF behavior change required msdft test change.
lrdf/test_lrdf: Lower numerical precision for unknown reason.
=> PySCF v2.8.0 compatibility

pyscf/mcpdft/otfnal.py, pyscf/mcpdft/test/test_pdft_veff.py
Translated GGA functionals `tN12` and `tGAM` (and other functionals relate to a b97 correlation function) had a numerical instability when calculation the 1- and 2- particle effective potential terms for systems with no beta electrons. This was related to the `idx` in `get_ratio`. This PR fixes the issue and adds tests to the `get_pdft_veff` and `get_pdft_feff` to prevent regression.
=> Fix PDFT effective potential numerical instability

pyscf/mcpdft/otfnal.py, pyscf/mcpdft/test/test_mgga.py
This pull request fixes a bug in `register_otfnal`. The previous implementation registers the new LibXC functional using lower case `xc_code`, which makes otfnal not able to find the new functional. Changing the LibXC functional code to upper case fixes the issue.
I also added unit tests for registering new otfnals.
=> Bug fix for register_otfnal

pyscf/mcpdft/otfnal.py, pyscf/mcpdft/test/test_mcpdft.py, pyscf/mcpdft/test/test_pdft_veff.py, pyscf/mcpdft/tfnal_derivs.py
PR #108 inadvertently caused all MC-PDFT calculations of molecules with all spin-up electrons to produce incorrect energies, which was not caught at the time because it turns out we had no actual unit tests of the **values** of the energies in that specific edge case.
=> Repair #108 and add all-spin-up unittest (#112)

pyscf/mcpdft/test/test_mcpdft.py
This is the test that keeps randomly failing just because of finite precision.
=> Loosen another mc-pdft tolerance

.github/workflows/ci.yml
From ubuntu-20.04, which is about to be unavailable. See https://github.com/pyscf/pyscf/issues/2721 and https://github.com/actions/runner-images/issues/11101.
=> Update CI runner to ubuntu-latest

pyscf/df/grad/lpdft.py, pyscf/df/grad/mcpdft.py, pyscf/df/grad/mspdft.py, pyscf/grad/cmspdft.py, pyscf/grad/lpdft.py, pyscf/grad/mcpdft.py, pyscf/grad/mspdft.py, pyscf/grad/test/test_diatomic_gradients.py, pyscf/grad/test/test_grad_cmspdft.py, pyscf/grad/test/test_grad_lpdft.py, pyscf/grad/test/test_grad_mcpdft.py, pyscf/grad/test/test_grad_mspdft.py, pyscf/mcpdft/mcpdft.py, pyscf/nac/mspdft.py
Will solve #119 (see thread for workaround in the meantime).
TODO:
=> Handling different types of mean-field bases in MC-PDFT calculations

pyscf/grad/test/test_grad_lpdft.py
I think it was a typo because all the other rohf grad san tests had 6 already
=> Loosen too-tight lpdft grad rohf san test tol

.gitignore, doc/mcpdft/README.md, pyscf/grad/mcpdft.py, pyscf/grad/test/test_grad_metagga_mcpdft.py, pyscf/mcpdft/mcpdft.py, pyscf/mcpdft/pdft_veff.py
Implements hybrid nuclear gradients for:
- SS-MC-PDFT 
- SS-MC-PDFT with density fitting
- SA-MC-PDFT
- SA-MC-PDFT with density fitting
Tests are added for MC23 with and without density fitting.
=> Hybrid MC-PDFT Nuclear Gradients

examples/grad/03-spin_flip_tda_grad.py, examples/grad/04-spin_flip_tddft_grad.py, examples/sftda/00-spin_flip_tddft.py, examples/sftda/01-spin_square.py, examples/sftda/02-test_transition_analyze.py, pyscf/sftda/__init__.py, pyscf/sftda/numint_sftd.py, pyscf/sftda/test/test_uks_sf_tda.py, pyscf/sftda/test/test_uks_sf_tddft.py, pyscf/sftda/uks_sf.py
Change the davidson solver for spin flip TDDFT, where lib.davidson_nosym1() is used. 
Unlike the case of spin-conserving TDDFT, the matrix in the Casida equation for spin-flip TDDFT (not TDA) is non-Hermitian, so the davidson_nosym1() solver should be used. The following updates have been made:
1. Changed davidson1() to davidson_nosym1() in sftda.uks_sf.kernel();
2. Added unit tests and usage examples for spin-flip TDDFT: (1) sftda.test.test_uks_sf_tddft.py；(2) example.grad.04-spin_flip_tddft_grad.py.
=> change the davidson solver for spin flip TDDFT

pyscf/mcpdft/mcpdft.py
See #128. Removes incorrect debug information that can lead to confusion.
Also warns users and points to the discussion if exchange and correlation are not scaled at the same amount. Perhaps this warning should eventually moved into `otfnal`.
=> Remove physically incorrect debug information in MC-PDFT

pyscf/mcpdft/__init__.py, pyscf/mcpdft/mcpdft.py, pyscf/prop/dip_moment/test/test_cmspdft_pdm.py
Also add a "simple usage" card to the top of `mcpdft/__init__.py` as suggested [here](https://github.com/pyscf/pyscf.github.io?tab=readme-ov-file#how-to-contribute).
=> Set default MSPDFT to L-PDFT (#138)
